const SCRAPED_DATA = [
  {
    "platform": "telegram",
    "handle": "rian_crimea",
    "name": "РИА Новости Крым",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 2604,
    "avg_views": 620,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/pGD-Ym6oon6lVWwD_UAAYs-kILSZ89yKwn4GpUpObFa7Je5CByR-EeLPlibT61ybHg_Sb6CAtEK6lPFtwlqr2gtQdTQB4Dyd4mLJyY3muiu5UK045g2X_RhLPYSolpffHYusL35heA8Q5gUZqLgBI26ZNaEo8X6OZQw4mlGAbAvn9JZclP671CkdFih4_f3qWurB5t3qqINj2SC330TAhvVn_QyWL_taJyd0-JyI45rn_Pg68ko96YZfgpKnsN-C1nboGDu1G-L5G_1dd3Wlk5-7iKlibBG9XgIcUuNeg2S1PkwzOZXJWTAaGBz0dH7voQS2C4uqbPHnLbzmVCJ7ng.jpg"
  },
  {
    "platform": "telegram",
    "handle": "chp_crimea",
    "name": "ЧП / Крым",
    "city": "Крым (Общий)",
    "category": "Происшествия",
    "audience": 142338,
    "avg_views": 33890,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/W1Ob_fdvU8IhAfLn71-tLy0XT5ncxvbnwHRMB4POgxSefGmAsU1NJxQrQMpklhlcS5bMG14NAX4oh3HnNiGr04yE38pUwN0XZtL65aKpzwOnEI_rZyalQWsu5Pbzy-m1vCUu4-EEjBin_4Kip6Sqd7r56RIoKdpujxCEIG30Dunu54_ekNoIocKBMxebzKgr2x523OTwNCu9oFwErYc1TpxHn6dz8FtZqWGO8Wx1IYnejDGvToQEaEErb7mCBWeBsAHpP1KTkKrEcnupPgvKp7LomTzuRwZdztPZUZYeiAsZJEBkNKrkt_3B7weruaaFLGoG2f-omzDjf17GyU1Uhg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "crimea24tv",
    "name": "Crimea24TV",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0,
    "avatar": "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIwIiBoZWlnaHQ9IjMyMCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI%2BPGRlZnM%2BPGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMCUiIHgyPSIwJSIgeTE9IjAlIiB5Mj0iMTAwJSI%2BPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzcyZDVmZCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzJhOWVmMSIvPjwvbGluZWFyR3JhZGllbnQ%2BPC9kZWZzPjxzdHlsZT50ZXh0e2ZvbnQ6NjAwIDQ0cHggLWFwcGxlLXN5c3RlbSxCbGlua01hY1N5c3RlbUZvbnQsJ1NlZ29lIFVJJyxSb2JvdG8sSGVsdmV0aWNhLEFyaWFsLHNhbnMtc2VyaWYsJ0FwcGxlIENvbG9yIEVtb2ppJywnU2Vnb2UgVUkgRW1vamknLCdTZWdvZSBVSSBTeW1ib2wnOy13ZWJraXQtdXNlci1zZWxlY3Q6bm9uZTt1c2VyLXNlbGVjdDpub25lfTwvc3R5bGU%2BPHJlY3Qgd2lkdGg9IjEwMCIgaGVpZ2h0PSIxMDAiIGZpbGw9InVybCgjZykiLz48dGV4dCB0ZXh0LWFuY2hvcj0ibWlkZGxlIiB4PSI1MCIgeT0iNjYiIGZpbGw9IiNmZmYiPkM8L3RleHQ%2BPC9zdmc%2B"
  },
  {
    "platform": "telegram",
    "handle": "minkurortov",
    "name": "Министерство туризма Крыма",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 1050,
    "avg_views": 250,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/kYmiD6LwMlUugQo5p17b8ZQ1M_0FspueIAeCdT9kSohTohh_ViAQqMD3o5LLsAmG9QvVdnKmWxUeUuG_0sMssZd0AgLDKnMuhpEmn-wGHEkMj5Lg2aVgrabsbAy0dw0MLByVpbPHwR_QPTe6z6YcWXYlerhm6HgD77AuZzsJdi563j7YoNK6OYExRgEn0KvOwXKXIUePo58yWJNP21oXGhrVcg9mxk4nbZisYjoR2tibfWauzlkKJM52hnGCRLuUgiM1iaB7V2Y69qIP9iCIo89afWMCNb1ij6o_5XOjyahm5M4sRdeKz-zpnzPPhe5jkPMZ_3noya6BqqyMXMYHiw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "sevastopol_news",
    "name": "Telegram: Contact @sevastopol_news",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "chp_sevastopol",
    "name": "ЧП / Севастополь",
    "city": "Севастополь",
    "category": "Происшествия",
    "audience": 271320,
    "avg_views": 64600,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/C-RFLUHQzAmPS-dh0VJaMww7XBh1d2Fjw2768lL-4fCysLMCQ8aTV7XacvW_R1vXpn8aZDzaPCaITh0UxUDqKPga2taHTYRg2xe_BnmPqbTaXJxZYcmAj_Is8TzZ3EHcV7Y3lsbMwm5IuQEKwh_RRIuPvt_8JFKF21mpRwmCeP9snQSM7toEnyQu6i69FdUsc-NP-qWcUME5o6FUfaaps1-hDOX6nUeCLcEuNCi5xpUX6XYAmxSTqkFgW0-Q3v3qLLwHEEfhvR2MCi9XnlScGjsOie26i-Cdt4FVeF0LUWYYv4XgOtrq5XgJ-ae27FIFSeaOEzBX3O9oWAONnm0I6Q.jpg"
  },
  {
    "platform": "telegram",
    "handle": "yalta_podslushano",
    "name": "Подслушано Ялта / Алушта",
    "city": "Ялта",
    "category": "Подслушано",
    "audience": 18685,
    "avg_views": 4449,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/mtdnsQpwsUGEf_CCMbxPW4nC7G_UdRdFXhE1Y5nbqmATORoOZSZoc6Ecivyqle1duIyAfV8hnAJMis7E87CjTTxSRmdlQhHTruVxj229Ep2H3R2XtpJTm1_jqIsr72LVk_gAswEXYbN8tu91k3iAIS0Y2egEs9IOqe-IUK2-D0JXC5WlyZKVs5qrDBCVj4RH0E9v4CuLpKfqe4x52BFiZ0pUefKBEW6RZE2fTRX_UyleBUx8DfvU_S7C1K2WVLFPTgJpvVe4Mtrk0Rfy3xNRv5eaQr6rFOnpkhlLXUI9VMvVhhCL0gZd_or_2PUTsJ6P44bP1Lv6t9zPXCQrraxGRg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "agp_yalta",
    "name": "АГП Ялта | Крым",
    "city": "Ялта",
    "category": "Новости",
    "audience": 5892,
    "avg_views": 1403,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/mA8D0QZCilreT0JNfVi3N9E_vWBMRcpCqCKCWRdrkBx_FgQfpfT8GuUX8Px1vVHbosxyzjsndGujy5XVmsCyGjr3ih1TMoxoGkzvaENHcZQIuSm1gZ-ehepxd5jigyTh9_NzeXwvOD6DfSXndn3CjU0Fec5YgAQ91qn7TvsidTinRg93NbRp_6FhiMXPwHP7q_4_vWNPUMs_9BHhdptYSC1PToQbbvtfXDrMVDNcBUneB1jWYeM3yRuaWXTqpT2ak47rPgt8in88KlAMUt-MfRFj9GeqeBn31r65quuOgU0TkDsNCvVDOs9QmnsYy3t08JDCv_SIxfMpCcwcZg7jbg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "kerch_news",
    "name": "Керчь ИНФО",
    "city": "Керчь",
    "category": "Новости",
    "audience": 6430,
    "avg_views": 1531,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/GSNtvvpydf8Vzzt_yfJGiUIUYioFOPirNHM2dUpSLzOUz5c2NKQvzx0AInNq6scTG8SgU8PiH5pD64yRmhc_zSRqe69IBTL9-yraGugdbu4K8psPZrYgKsiTDhcjt8asLagGZGat9c-d0KwKVDZuqtSbJMN0Vw4wzQ1zzBZjFRjYVYJLH3dXg6KTRtZ3pwRl5GiDl21wZgtzZi5vHuTX3JAO_YfYZGe9y0ngFfRQwXjUX2jzdVhAP7_1V4WUW1ZZgXJ4qKvisJWnfFop9riS1HplfssgVNH--rEkf8PI4U7UNE5R9k9_UWjhJKKssL7dLXavK7N2MnY8jRQ5wwNTyw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "seanewskerch",
    "name": "МыКЕРЧЬ.РФ - новости Крыма",
    "city": "Керчь",
    "category": "Новости",
    "audience": 5850,
    "avg_views": 1393,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/Zw02PSGhC9xAHo50PY5fBbpY0zuWRn_86ER39a2QXOSjzgAglRhJ2OOLJ8dM5zIgb4pDcUkZi0tC4bExh-WihnzrGGhXjXnFtLELpnhSqVUeaKaq7KI5l0QwBD82saHmApIJmBNHQe0Tp1K_c7BFvicanDx40QA6QwN4JvdP1_SoLPWzxCuoeznqY2hp9yxVjm-tWq5dWWuKQW4e30TR5TE8pJfNCpFwy__I1NElxueD4hlBy2wAzPvh0INNnCV5Q1f2zRYjKf6F2tp6Dg_sF7V_IWgQ2MRCNaFpB_UiTOj6f81ycGH26iRbfzQJxt4VanUcbEZ8Xrynbre-Lr7uHA.jpg"
  },
  {
    "platform": "telegram",
    "handle": "evpa_chp",
    "name": "Евпатория ЧП 🔥",
    "city": "Евпатория",
    "category": "Происшествия",
    "audience": 11604,
    "avg_views": 2763,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/bNopJVYkT0s2rl0NBI8fuxSAiQ1__JktzqrF4vng0uxlcE03byMOe7n5wsv4WWoeJbF60QUweDNOVVxabqcQsaO0icRJzCF5odMIglqBmfnpPR1aFcRB8nAbL5YiTZlU9l46pwl6TGfjqez70GmVcmojHOUHSQ5vP7rB9H7X0Dwv6a71Uwl9vknNjBNwF3SMyvSI2nNDsU48n7rXeW4YPS7T0iccFH0zZ8PfLbeP6qLTxorILl5WpSrQc5NnqcbeeicF9zEtyuCj-uLfljZnB-8E3nqh-xhlf18SBaX_q36onUI6KLT56tNqgT2UQeiXND7G6GOpj4XHZebZvKxwoA.jpg"
  },
  {
    "platform": "telegram",
    "handle": "evp_pod",
    "name": "📣 Евпатория Подслушано (Крым)",
    "city": "Евпатория",
    "category": "Подслушано",
    "audience": 2994,
    "avg_views": 713,
    "avg_likes": 0,
    "engagement_rate": 23.81,
    "avatar": "https://cdn4.telesco.pe/file/gYn8_T_fVdWvGqtIPyNtH8_12-ZUwxtfTwZ3gLgyErsd7Ux-mB5vrh7i70ZteFaH_l_LAxcAYAXLRandy8TN1QMfzXSd615Q2KgsQZALpaHHzVaDY5c-eh09vwrbF5pbzGKStmiMWAKX0hoDGyjkM178qu69BS4JlYeYCxOTBVvIaaMzY-0NmZ5ccJTc2d_1LExZ-TYOuGiwfirHdO6JtOtGmwtMV5ph650WqwrbFx-hmSRNrDAxtmqUPkDvWJhuoljvHxO6EoxyLKOfPhrKhLrfdfxqY16gqXoTucUpu1jIIHmRIixINhVfLCV6AeLL07gi5ET8aBKNOxnno3l7rg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "feodosia_news",
    "name": "Новость|Феодосия",
    "city": "Феодосия",
    "category": "Новости",
    "audience": 109,
    "avg_views": 26,
    "avg_likes": 0,
    "engagement_rate": 23.85,
    "avatar": "https://cdn4.telesco.pe/file/o7vjyICJMxGetZuFTMdQKMJMXI6NJxGpT7k-pM7vSiihRCRpaITWO-dWcTWZTSlWPHMm4rbSHsAbi3azjCk-ovbUohZc6ycH9zhKZEeXu4fStPVqUmYm5MEtECFhHLZRZ_S8veiv1kHsxyinkvxzlP_2AJIED-xOQ_ALbeDgkmOT3c2BpgLYUMIwy6Fjhrxccy2F8sL5hYIUfEjlan200YsHw8EL7e1YjV7JFT0CRUDOuXcXpG9_6TgkIoDPCWXZCxT_eWezWLrwAK0ErVKTqkSjLYRZKZ4VQX74Q37TX-O_LXsSrxT-HRhhjveB3ZEwgbatqp1LzWwPgUgIck7GSw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "feodosia_chp",
    "name": "Telegram: Contact @feodosia_chp",
    "city": "Feodosia",
    "category": "Происшествия",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "vk",
    "handle": "typical_simferopol",
    "name": "Это Симферополь, детка! [Типичный Симферополь]",
    "city": "Симферополь",
    "category": "Подслушано",
    "audience": 1000,
    "avg_views": 67,
    "avg_likes": 4,
    "engagement_rate": 0.73,
    "avatar": "http://sun9-63.userapi.com/s/v1/ig2/vB6uKfAdvlunmx_DgRbqqXKgmQILAQR3u9eVjnaVL-iG8BKG110Kreytk_UAE3BqDQVN_Z7PWq2Qc2x0EyNrn4D0.jpg?quality=96&crop=0,0,230,230&as=32x32,48x48,72x72,108x108,160x160&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "simferopol_city",
    "name": "Мой Симферополь",
    "city": "Симферополь",
    "category": "Общество",
    "audience": 4750,
    "avg_views": 458,
    "avg_likes": 19,
    "engagement_rate": 0.88,
    "avatar": "http://sun9-75.userapi.com/impf/R2KAqxbio05geH1mpTQH8GVCcBRY4QDw3lP3Tw/mm6J2lcfqfk.jpg?size=1920x768&quality=95&crop=0,213,1280,511&sign=4c3fc6a623b3a509ac4abec7161fc651&type=cover_group"
  },
  {
    "platform": "vk",
    "handle": "sevastopol_groupe",
    "name": "Севастополь",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 96298,
    "avg_views": 5010,
    "avg_likes": 255,
    "engagement_rate": 0.52,
    "avatar": "http://sun1-14.userapi.com/impf/UKQ19dMlN3BB7Lv_4S1RikhOQhksnqpb1cAU8A/LXvwjCuAP3Q.jpg?size=1818x606&quality=95&crop=0,0,1590,530&sign=542db9aaaacba1dabd905946b4f41a9a&type=cover_group"
  },
  {
    "platform": "vk",
    "handle": "sevas_92",
    "name": "Подслушано Севастополь",
    "city": "Севастополь",
    "category": "Подслушано",
    "audience": 114775,
    "avg_views": 438,
    "avg_likes": 0,
    "engagement_rate": 0.02,
    "avatar": "http://sun1-56.userapi.com/s/v1/ig2/_wbbC5VK-_0A0up0piPGYU_9lpgTmqagOcxXuBtRZlpkQIadgXPpVIwSl6txgz8Oqw8d4y4D_J4H9SR_PpdKPcOS.jpg?quality=95&crop=0,0,1080,1080&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720,1080x1080&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "typical_sevastopol",
    "name": "✪  ✪ Паблик 3 ✪ 2026",
    "city": "Севастополь",
    "category": "Общество",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0.0,
    "avatar": "http://sun9-86.userapi.com/impg/9FmuZgmL8ElIl3ap2VNqqvCJuR3XBTRcL5RstQ/IkJdt6c43WI.jpg?quality=96&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360&sign=80af15cf714eb8b0c9b0fb180d3fb037&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "podslushano_yalta",
    "name": "ПОДСЛУШАНО ЯЛТА",
    "city": "Ялта",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0.0,
    "avatar": "https://ui-avatars.com/api/?name=ПОДСЛУШАНО ЯЛТА&background=random"
  },
  {
    "platform": "vk",
    "handle": "yalta_gorod_schastya",
    "name": "Филиал ПОДСЛУШАНО в ЯЛТЕ",
    "city": "Ялта",
    "category": "Туризм",
    "audience": 15000,
    "avg_views": 12,
    "avg_likes": 0,
    "engagement_rate": 0.0,
    "avatar": "http://sun1-54.userapi.com/s/v1/ig1/u1qa5FAI-geuGmqTNorK4kG_xgSaAYjqi3FAi-cwb7yHmcC-cABvQ_mjTeH937gQpcq4v_3y.jpg?quality=96&crop=0,0,720,720&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "podslushano_kerch",
    "name": "ПОДСЛУШАНО | КЕРЧЬ",
    "city": "Керчь",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0.0,
    "avatar": "https://ui-avatars.com/api/?name=ПОДСЛУШАНО | КЕРЧЬ&background=random"
  },
  {
    "platform": "vk",
    "handle": "kerch_segodnya",
    "name": "КЕРЧЬ СЕГОДНЯ",
    "city": "Керчь",
    "category": "Новости",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0.0,
    "avatar": "https://ui-avatars.com/api/?name=КЕРЧЬ СЕГОДНЯ&background=random"
  },
  {
    "platform": "vk",
    "handle": "evpator_podslushano",
    "name": "Евпатория | Подслушано",
    "city": "Евпатория",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0.0,
    "avatar": "https://ui-avatars.com/api/?name=Евпатория | Подслушано&background=random"
  },
  {
    "platform": "vk",
    "handle": "evpator_ru",
    "name": "Евпатория -  наш город !!!",
    "city": "Евпатория",
    "category": "Новости",
    "audience": 39222,
    "avg_views": 195,
    "avg_likes": 3,
    "engagement_rate": 0.03,
    "avatar": "http://sun9-55.userapi.com/QK-pgYWE0orEYxJfRLpw-eaUh5Z0C0tKKQgX5A/m-9qfd9jjaM.jpg"
  },
  {
    "platform": "vk",
    "handle": "podslushano_feodosiya",
    "name": "Подслушано Феодосия",
    "city": "Феодосия",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "engagement_rate": 0.0,
    "avatar": "https://ui-avatars.com/api/?name=Подслушано Феодосия&background=random"
  },
  {
    "platform": "instagram",
    "handle": "crimea_life",
    "name": "Крым Life",
    "city": "Крым (Общий)",
    "category": "Стиль жизни",
    "audience": 78300,
    "avg_views": 18200,
    "avg_likes": 2400,
    "engagement_rate": 3.53,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "more.kryma",
    "name": "Море Крыма",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 112000,
    "avg_views": 32000,
    "avg_likes": 4100,
    "engagement_rate": 4.23,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "typical_simferopol",
    "name": "Типичный Симферополь",
    "city": "Симферополь",
    "category": "Общество",
    "audience": 43500,
    "avg_views": 8900,
    "avg_likes": 1150,
    "engagement_rate": 3.05,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "sevastopol_life",
    "name": "Севастополь Life",
    "city": "Севастополь",
    "category": "Общество",
    "audience": 52100,
    "avg_views": 11200,
    "avg_likes": 1540,
    "engagement_rate": 3.39,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "yalta_life",
    "name": "Ялта Life",
    "city": "Ялта",
    "category": "Общество",
    "audience": 61200,
    "avg_views": 14500,
    "avg_likes": 1920,
    "engagement_rate": 3.61,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "kerch_info",
    "name": "Керчь Инфо",
    "city": "Керчь",
    "category": "Новости",
    "audience": 31400,
    "avg_views": 6200,
    "avg_likes": 790,
    "engagement_rate": 2.91,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "x",
    "handle": "CrimeaUA1",
    "name": "Крымский бандеровец",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 158000,
    "avg_views": 25000,
    "avg_likes": 1420,
    "engagement_rate": 1.22,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "x",
    "handle": "CrimeaRepublic",
    "name": "Республика Крым",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 12500,
    "avg_views": 1100,
    "avg_likes": 45,
    "engagement_rate": 0.54,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "x",
    "handle": "SimferopolNews",
    "name": "Новости Симферополя",
    "city": "Симферополь",
    "category": "Новости",
    "audience": 8700,
    "avg_views": 850,
    "avg_likes": 32,
    "engagement_rate": 0.56,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "x",
    "handle": "SevastopolNews",
    "name": "Новости Севастополя",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 9300,
    "avg_views": 920,
    "avg_likes": 38,
    "engagement_rate": 0.61,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "ok",
    "handle": "vesticrimea",
    "name": "Вести Крым",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 24500,
    "avg_views": 4800,
    "avg_likes": 120,
    "engagement_rate": 0.88,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "crimea24tv",
    "name": "Крым 24",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 18200,
    "avg_views": 3500,
    "avg_likes": 95,
    "engagement_rate": 0.91,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "typical_simferopol",
    "name": "Типичный Симферополь",
    "city": "Симферополь",
    "category": "Подслушано",
    "audience": 12500,
    "avg_views": 2100,
    "avg_likes": 55,
    "engagement_rate": 0.78,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  }
];