const SCRAPED_DATA = [
  {
    "platform": "telegram",
    "handle": "rian_crimea",
    "name": "РИА Новости Крым",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 36198,
    "avg_views": 623,
    "avg_likes": 0,
    "avg_comments": 3,
    "avg_reposts": 7,
    "posts_per_day": 6,
    "engagement_rate": 0.03,
    "err_rate": 1.61,
    "avatar": "https://cdn4.telesco.pe/file/pGD-Ym6oon6lVWwD_UAAYs-kILSZ89yKwn4GpUpObFa7Je5CByR-EeLPlibT61ybHg_Sb6CAtEK6lPFtwlqr2gtQdTQB4Dyd4mLJyY3muiu5UK045g2X_RhLPYSolpffHYusL35heA8Q5gUZqLgBI26ZNaEo8X6OZQw4mlGAbAvn9JZclP671CkdFih4_f3qWurB5t3qqINj2SC330TAhvVn_QyWL_taJyd0-JyI45rn_Pg68ko96YZfgpKnsN-C1nboGDu1G-L5G_1dd3Wlk5-7iKlibBG9XgIcUuNeg2S1PkwzOZXJWTAaGBz0dH7voQS2C4uqbPHnLbzmVCJ7ng.jpg"
  },
  {
    "platform": "telegram",
    "handle": "chp_crimea",
    "name": "ЧП / Крым",
    "city": "Крым (Общий)",
    "category": "Происшествия",
    "audience": 458007,
    "avg_views": 32730,
    "avg_likes": 0,
    "avg_comments": 163,
    "avg_reposts": 392,
    "posts_per_day": 6,
    "engagement_rate": 0.12,
    "err_rate": 1.7,
    "avatar": "https://cdn4.telesco.pe/file/W1Ob_fdvU8IhAfLn71-tLy0XT5ncxvbnwHRMB4POgxSefGmAsU1NJxQrQMpklhlcS5bMG14NAX4oh3HnNiGr04yE38pUwN0XZtL65aKpzwOnEI_rZyalQWsu5Pbzy-m1vCUu4-EEjBin_4Kip6Sqd7r56RIoKdpujxCEIG30Dunu54_ekNoIocKBMxebzKgr2x523OTwNCu9oFwErYc1TpxHn6dz8FtZqWGO8Wx1IYnejDGvToQEaEErb7mCBWeBsAHpP1KTkKrEcnupPgvKp7LomTzuRwZdztPZUZYeiAsZJEBkNKrkt_3B7weruaaFLGoG2f-omzDjf17GyU1Uhg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "crimea_chp",
    "name": "ЧП / КРЫМ 🆘🔞",
    "city": "Крым (Общий)",
    "category": "Происшествия",
    "audience": 83623,
    "avg_views": 4110,
    "avg_likes": 0,
    "avg_comments": 20,
    "avg_reposts": 49,
    "posts_per_day": 6,
    "engagement_rate": 0.08,
    "err_rate": 1.68,
    "avatar": "https://cdn4.telesco.pe/file/ky5fvPW-rO9l9tu6nMwhRIomV_OxHEV7-bYcLqFT_aMvRFwb0XV3oF89PaUwAJUdipSLB-TaTLnmbqaLv2lNrJhxF_1LQaWZ-TRcNL6ulZGt9_F_7kT0QHM0mljEDd2LisqxDTy3L773zyUZfZAvFLNAUHA59kO1ZNSb4K629veUUSObjhkWzkEr9t_DBjJTO7QfnT1xmqS1QO8McthCWC_sLshccv5ajK3BPJ3sPL_fF-VAAhsCwEsFtkN_fwDQHhUGWZOHFfhCHojj_eW22xApjHnFIly7Zo4KdjnNFCDrpCmWeu06LeyNo9c9uXZZ5KipvSrzyCov7D0BFFRyfw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "minkurortov",
    "name": "Министерство туризма Крыма",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 4787,
    "avg_views": 253,
    "avg_likes": 0,
    "avg_comments": 1,
    "avg_reposts": 3,
    "posts_per_day": 6,
    "engagement_rate": 0.08,
    "err_rate": 1.58,
    "avatar": "https://cdn4.telesco.pe/file/kYmiD6LwMlUugQo5p17b8ZQ1M_0FspueIAeCdT9kSohTohh_ViAQqMD3o5LLsAmG9QvVdnKmWxUeUuG_0sMssZd0AgLDKnMuhpEmn-wGHEkMj5Lg2aVgrabsbAy0dw0MLByVpbPHwR_QPTe6z6YcWXYlerhm6HgD77AuZzsJdi563j7YoNK6OYExRgEn0KvOwXKXIUePo58yWJNP21oXGhrVcg9mxk4nbZisYjoR2tibfWauzlkKJM52hnGCRLuUgiM1iaB7V2Y69qIP9iCIo89afWMCNb1ij6o_5XOjyahm5M4sRdeKz-zpnzPPhe5jkPMZ_3noya6BqqyMXMYHiw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "chp_sevastopol",
    "name": "ЧП / Севастополь",
    "city": "Севастополь",
    "category": "Происшествия",
    "audience": 383239,
    "avg_views": 60140,
    "avg_likes": 0,
    "avg_comments": 300,
    "avg_reposts": 721,
    "posts_per_day": 6,
    "engagement_rate": 0.27,
    "err_rate": 1.7,
    "avatar": "https://cdn4.telesco.pe/file/C-RFLUHQzAmPS-dh0VJaMww7XBh1d2Fjw2768lL-4fCysLMCQ8aTV7XacvW_R1vXpn8aZDzaPCaITh0UxUDqKPga2taHTYRg2xe_BnmPqbTaXJxZYcmAj_Is8TzZ3EHcV7Y3lsbMwm5IuQEKwh_RRIuPvt_8JFKF21mpRwmCeP9snQSM7toEnyQu6i69FdUsc-NP-qWcUME5o6FUfaaps1-hDOX6nUeCLcEuNCi5xpUX6XYAmxSTqkFgW0-Q3v3qLLwHEEfhvR2MCi9XnlScGjsOie26i-Cdt4FVeF0LUWYYv4XgOtrq5XgJ-ae27FIFSeaOEzBX3O9oWAONnm0I6Q.jpg"
  },
  {
    "platform": "telegram",
    "handle": "yalta_podslushano",
    "name": "Подслушано Ялта / Алушта",
    "city": "Ялта",
    "category": "Подслушано",
    "audience": 41886,
    "avg_views": 4674,
    "avg_likes": 0,
    "avg_comments": 23,
    "avg_reposts": 56,
    "posts_per_day": 6,
    "engagement_rate": 0.19,
    "err_rate": 1.69,
    "avatar": "https://cdn4.telesco.pe/file/mtdnsQpwsUGEf_CCMbxPW4nC7G_UdRdFXhE1Y5nbqmATORoOZSZoc6Ecivyqle1duIyAfV8hnAJMis7E87CjTTxSRmdlQhHTruVxj229Ep2H3R2XtpJTm1_jqIsr72LVk_gAswEXYbN8tu91k3iAIS0Y2egEs9IOqe-IUK2-D0JXC5WlyZKVs5qrDBCVj4RH0E9v4CuLpKfqe4x52BFiZ0pUefKBEW6RZE2fTRX_UyleBUx8DfvU_S7C1K2WVLFPTgJpvVe4Mtrk0Rfy3xNRv5eaQr6rFOnpkhlLXUI9VMvVhhCL0gZd_or_2PUTsJ6P44bP1Lv6t9zPXCQrraxGRg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "agp_yalta",
    "name": "АГП Ялта | Крым",
    "city": "Ялта",
    "category": "Новости",
    "audience": 11508,
    "avg_views": 1487,
    "avg_likes": 0,
    "avg_comments": 7,
    "avg_reposts": 17,
    "posts_per_day": 6,
    "engagement_rate": 0.21,
    "err_rate": 1.61,
    "avatar": "https://cdn4.telesco.pe/file/mA8D0QZCilreT0JNfVi3N9E_vWBMRcpCqCKCWRdrkBx_FgQfpfT8GuUX8Px1vVHbosxyzjsndGujy5XVmsCyGjr3ih1TMoxoGkzvaENHcZQIuSm1gZ-ehepxd5jigyTh9_NzeXwvOD6DfSXndn3CjU0Fec5YgAQ91qn7TvsidTinRg93NbRp_6FhiMXPwHP7q_4_vWNPUMs_9BHhdptYSC1PToQbbvtfXDrMVDNcBUneB1jWYeM3yRuaWXTqpT2ak47rPgt8in88KlAMUt-MfRFj9GeqeBn31r65quuOgU0TkDsNCvVDOs9QmnsYy3t08JDCv_SIxfMpCcwcZg7jbg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "kerch_news",
    "name": "Керчь ИНФО",
    "city": "Керчь",
    "category": "Новости",
    "audience": 37159,
    "avg_views": 1507,
    "avg_likes": 0,
    "avg_comments": 7,
    "avg_reposts": 18,
    "posts_per_day": 6,
    "engagement_rate": 0.07,
    "err_rate": 1.66,
    "avatar": "https://cdn4.telesco.pe/file/GSNtvvpydf8Vzzt_yfJGiUIUYioFOPirNHM2dUpSLzOUz5c2NKQvzx0AInNq6scTG8SgU8PiH5pD64yRmhc_zSRqe69IBTL9-yraGugdbu4K8psPZrYgKsiTDhcjt8asLagGZGat9c-d0KwKVDZuqtSbJMN0Vw4wzQ1zzBZjFRjYVYJLH3dXg6KTRtZ3pwRl5GiDl21wZgtzZi5vHuTX3JAO_YfYZGe9y0ngFfRQwXjUX2jzdVhAP7_1V4WUW1ZZgXJ4qKvisJWnfFop9riS1HplfssgVNH--rEkf8PI4U7UNE5R9k9_UWjhJKKssL7dLXavK7N2MnY8jRQ5wwNTyw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "seanewskerch",
    "name": "МыКЕРЧЬ.РФ - новости Крыма",
    "city": "Керчь",
    "category": "Новости",
    "audience": 23581,
    "avg_views": 1329,
    "avg_likes": 0,
    "avg_comments": 6,
    "avg_reposts": 15,
    "posts_per_day": 6,
    "engagement_rate": 0.09,
    "err_rate": 1.58,
    "avatar": "https://cdn4.telesco.pe/file/Zw02PSGhC9xAHo50PY5fBbpY0zuWRn_86ER39a2QXOSjzgAglRhJ2OOLJ8dM5zIgb4pDcUkZi0tC4bExh-WihnzrGGhXjXnFtLELpnhSqVUeaKaq7KI5l0QwBD82saHmApIJmBNHQe0Tp1K_c7BFvicanDx40QA6QwN4JvdP1_SoLPWzxCuoeznqY2hp9yxVjm-tWq5dWWuKQW4e30TR5TE8pJfNCpFwy__I1NElxueD4hlBy2wAzPvh0INNnCV5Q1f2zRYjKf6F2tp6Dg_sF7V_IWgQ2MRCNaFpB_UiTOj6f81ycGH26iRbfzQJxt4VanUcbEZ8Xrynbre-Lr7uHA.jpg"
  },
  {
    "platform": "telegram",
    "handle": "evpa_chp",
    "name": "Евпатория ЧП 🔥",
    "city": "Евпатория",
    "category": "Происшествия",
    "audience": 53515,
    "avg_views": 2815,
    "avg_likes": 0,
    "avg_comments": 14,
    "avg_reposts": 33,
    "posts_per_day": 6,
    "engagement_rate": 0.09,
    "err_rate": 1.67,
    "avatar": "https://cdn4.telesco.pe/file/bNopJVYkT0s2rl0NBI8fuxSAiQ1__JktzqrF4vng0uxlcE03byMOe7n5wsv4WWoeJbF60QUweDNOVVxabqcQsaO0icRJzCF5odMIglqBmfnpPR1aFcRB8nAbL5YiTZlU9l46pwl6TGfjqez70GmVcmojHOUHSQ5vP7rB9H7X0Dwv6a71Uwl9vknNjBNwF3SMyvSI2nNDsU48n7rXeW4YPS7T0iccFH0zZ8PfLbeP6qLTxorILl5WpSrQc5NnqcbeeicF9zEtyuCj-uLfljZnB-8E3nqh-xhlf18SBaX_q36onUI6KLT56tNqgT2UQeiXND7G6GOpj4XHZebZvKxwoA.jpg"
  },
  {
    "platform": "telegram",
    "handle": "evp_pod",
    "name": "📣 Евпатория Подслушано (Крым)",
    "city": "Евпатория",
    "category": "Подслушано",
    "audience": 9183,
    "avg_views": 739,
    "avg_likes": 0,
    "avg_comments": 3,
    "avg_reposts": 8,
    "posts_per_day": 6,
    "engagement_rate": 0.12,
    "err_rate": 1.49,
    "avatar": "https://cdn4.telesco.pe/file/gYn8_T_fVdWvGqtIPyNtH8_12-ZUwxtfTwZ3gLgyErsd7Ux-mB5vrh7i70ZteFaH_l_LAxcAYAXLRandy8TN1QMfzXSd615Q2KgsQZALpaHHzVaDY5c-eh09vwrbF5pbzGKStmiMWAKX0hoDGyjkM178qu69BS4JlYeYCxOTBVvIaaMzY-0NmZ5ccJTc2d_1LExZ-TYOuGiwfirHdO6JtOtGmwtMV5ph650WqwrbFx-hmSRNrDAxtmqUPkDvWJhuoljvHxO6EoxyLKOfPhrKhLrfdfxqY16gqXoTucUpu1jIIHmRIixINhVfLCV6AeLL07gi5ET8aBKNOxnno3l7rg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "mash_na_volne",
    "name": "Mash на волне",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 66859,
    "avg_views": 54413,
    "avg_likes": 0,
    "avg_comments": 272,
    "avg_reposts": 652,
    "posts_per_day": 6,
    "engagement_rate": 1.38,
    "err_rate": 1.7,
    "avatar": "https://cdn4.telesco.pe/file/UygTT0uZB3oBtkyr1HwntqDEwccktqNs1sM1m3W3o9oXHZH65l6Q2mX8ZfOfokLM2-O8gpcVQk8fUm1eA5a_qWUl7KnnyavuHYPZvl0cUvcCzWEMrpEZC3k6c6_ehL1tKAWcD_4FH_MD2tpkzi4OjyRDyhz_oJbX43NRHpBTXI9rhe_GBux9JuyO1vtf6P1GhlBHaiNAyz6u9-hg4vnT5a1JEMXkWFK22SfdpGHvOUle-w4zLTbvMBVViCxKdAYmEWuOQkH7Hpc7IZqLxNZ2e0WBZDUyQMv_cjUwJvcIP9FXpellmd_T-sLscqrfJZypGoN_UQtKZ_REjYtaJ8gclg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "vesticrimea",
    "name": "ВЕСТИ КРЫМ",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 18892,
    "avg_views": 454,
    "avg_likes": 0,
    "avg_comments": 2,
    "avg_reposts": 5,
    "posts_per_day": 6,
    "engagement_rate": 0.04,
    "err_rate": 1.54,
    "avatar": "https://cdn4.telesco.pe/file/POBq2gbUIBkhXtDiLkXdJt5bTThnU0nSLhG63_AsS-z2xi6qyTEIg-PY7o2vuT6kRnPWT4D5P-8exTyLdnubjkl_wl2FC4qUx17fw8TunHkSKql-Rm_Qnsov4unAkWmOx9RHUeBTll1rnjQT2F0QdKRSbLbeCS0OoYvtsiIW3EWahL1VXpv_17WGc14ScWcBvi_r7G8ys-1o2YMpWfKm3eSj_cKy2fW31jJV5C_hDFtO84NKBdNsEq7c3U1ZjmvTWINxSiTVz8Xu-q-wHTysOj-KKk9xPoLaKHq4EQUlQDD1StjJLAPti9-CZ4ecURSmIqd3_iRz8HB9T_3VvEIp2A.jpg"
  },
  {
    "platform": "vk",
    "handle": "typical_simferopol",
    "name": "Это Симферополь, детка! [Типичный Симферополь]",
    "city": "Симферополь",
    "category": "Подслушано",
    "audience": 320000,
    "avg_views": 67,
    "avg_likes": 4,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 5.97,
    "avatar": "http://sun9-63.userapi.com/s/v1/ig2/vB6uKfAdvlunmx_DgRbqqXKgmQILAQR3u9eVjnaVL-iG8BKG110Kreytk_UAE3BqDQVN_Z7PWq2Qc2x0EyNrn4D0.jpg?quality=96&crop=0,0,230,230&as=32x32,48x48,72x72,108x108,160x160&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "simferopol_city",
    "name": "Мой Симферополь",
    "city": "Симферополь",
    "category": "Общество",
    "audience": 85000,
    "avg_views": 458,
    "avg_likes": 19,
    "avg_comments": 2,
    "avg_reposts": 3,
    "posts_per_day": 5,
    "engagement_rate": 0.03,
    "err_rate": 5.24,
    "avatar": "http://sun9-75.userapi.com/impf/R2KAqxbio05geH1mpTQH8GVCcBRY4QDw3lP3Tw/mm6J2lcfqfk.jpg?size=1920x768&quality=95&crop=0,213,1280,511&sign=4c3fc6a623b3a509ac4abec7161fc651&type=cover_group"
  },
  {
    "platform": "vk",
    "handle": "sevastopol_groupe",
    "name": "Севастополь",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 96299,
    "avg_views": 5130,
    "avg_likes": 259,
    "avg_comments": 25,
    "avg_reposts": 41,
    "posts_per_day": 5,
    "engagement_rate": 0.34,
    "err_rate": 6.34,
    "avatar": "http://sun1-14.userapi.com/impf/UKQ19dMlN3BB7Lv_4S1RikhOQhksnqpb1cAU8A/LXvwjCuAP3Q.jpg?size=1818x606&quality=95&crop=0,0,1590,530&sign=542db9aaaacba1dabd905946b4f41a9a&type=cover_group"
  },
  {
    "platform": "vk",
    "handle": "sevas_92",
    "name": "Подслушано Севастополь",
    "city": "Севастополь",
    "category": "Подслушано",
    "audience": 114775,
    "avg_views": 275,
    "avg_likes": 290,
    "avg_comments": 1,
    "avg_reposts": 2,
    "posts_per_day": 5,
    "engagement_rate": 0.26,
    "err_rate": 106.55,
    "avatar": "http://sun1-56.userapi.com/s/v1/ig2/_wbbC5VK-_0A0up0piPGYU_9lpgTmqagOcxXuBtRZlpkQIadgXPpVIwSl6txgz8Oqw8d4y4D_J4H9SR_PpdKPcOS.jpg?quality=95&crop=0,0,1080,1080&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720,1080x1080&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "typical_sevastopol",
    "name": "✪  ✪ Паблик 3 ✪ 2026",
    "city": "Севастополь",
    "category": "Общество",
    "audience": 210000,
    "avg_views": 32000,
    "avg_likes": 380,
    "avg_comments": 160,
    "avg_reposts": 256,
    "posts_per_day": 5,
    "engagement_rate": 0.38,
    "err_rate": 2.49,
    "avatar": "http://sun9-86.userapi.com/impg/9FmuZgmL8ElIl3ap2VNqqvCJuR3XBTRcL5RstQ/IkJdt6c43WI.jpg?quality=96&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360&sign=80af15cf714eb8b0c9b0fb180d3fb037&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "yalta_overheard",
    "name": "Подслушано в Ялте",
    "city": "Ялта",
    "category": "Подслушано",
    "audience": 75000,
    "avg_views": 11000,
    "avg_likes": 130,
    "avg_comments": 55,
    "avg_reposts": 88,
    "posts_per_day": 5,
    "engagement_rate": 0.36,
    "err_rate": 2.48,
    "avatar": "http://sun1-55.userapi.com/s/v1/ig1/VDjL2fpfY7_5D4X9Mh-v6PdRN1z_8UUnQ7Slqx3BDPuVuiM0WbtOA2tPKipiB3x8ZgEuoNqy.jpg?quality=96&crop=0,310,496,496&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "yalta_gorod_schastya",
    "name": "Филиал ПОДСЛУШАНО в ЯЛТЕ",
    "city": "Ялта",
    "category": "Туризм",
    "audience": 48000,
    "avg_views": 12,
    "avg_likes": 190,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.4,
    "err_rate": 1583.33,
    "avatar": "http://sun1-54.userapi.com/s/v1/ig1/u1qa5FAI-geuGmqTNorK4kG_xgSaAYjqi3FAi-cwb7yHmcC-cABvQ_mjTeH937gQpcq4v_3y.jpg?quality=96&crop=0,0,720,720&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "podslushano_kerch",
    "name": "ПОДСЛУШАНО | КЕРЧЬ",
    "city": "Керчь",
    "category": "Подслушано",
    "audience": 62000,
    "avg_views": 8500,
    "avg_likes": 110,
    "avg_comments": 42,
    "avg_reposts": 68,
    "posts_per_day": 5,
    "engagement_rate": 0.35,
    "err_rate": 2.59,
    "avatar": "https://ui-avatars.com/api/?name=ПОДСЛУШАНО | КЕРЧЬ&background=random"
  },
  {
    "platform": "vk",
    "handle": "kerch_segodnya",
    "name": "КЕРЧЬ СЕГОДНЯ",
    "city": "Керчь",
    "category": "Новости",
    "audience": 38000,
    "avg_views": 6200,
    "avg_likes": 85,
    "avg_comments": 31,
    "avg_reposts": 49,
    "posts_per_day": 5,
    "engagement_rate": 0.43,
    "err_rate": 2.66,
    "avatar": "https://ui-avatars.com/api/?name=КЕРЧЬ СЕГОДНЯ&background=random"
  },
  {
    "platform": "vk",
    "handle": "evpator_podslushano",
    "name": "Евпатория | Подслушано",
    "city": "Евпатория",
    "category": "Подслушано",
    "audience": 43000,
    "avg_views": 7100,
    "avg_likes": 90,
    "avg_comments": 35,
    "avg_reposts": 56,
    "posts_per_day": 5,
    "engagement_rate": 0.42,
    "err_rate": 2.55,
    "avatar": "https://ui-avatars.com/api/?name=Евпатория | Подслушано&background=random"
  },
  {
    "platform": "vk",
    "handle": "evpator_ru",
    "name": "Евпатория -  наш город !!!",
    "city": "Евпатория",
    "category": "Новости",
    "audience": 39222,
    "avg_views": 320,
    "avg_likes": 5,
    "avg_comments": 1,
    "avg_reposts": 2,
    "posts_per_day": 5,
    "engagement_rate": 0.02,
    "err_rate": 2.5,
    "avatar": "http://sun1-55.userapi.com/QK-pgYWE0orEYxJfRLpw-eaUh5Z0C0tKKQgX5A/m-9qfd9jjaM.jpg"
  },
  {
    "platform": "vk",
    "handle": "podslushano_feodosiya",
    "name": "Подслушано Феодосия",
    "city": "Феодосия",
    "category": "Подслушано",
    "audience": 35000,
    "avg_views": 5900,
    "avg_likes": 75,
    "avg_comments": 29,
    "avg_reposts": 47,
    "posts_per_day": 5,
    "engagement_rate": 0.43,
    "err_rate": 2.56,
    "avatar": "https://ui-avatars.com/api/?name=Подслушано Феодосия&background=random"
  },
  {
    "platform": "vk",
    "handle": "mash.na.volne",
    "name": "Mash на волне (ВК)",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 98000,
    "avg_views": 22000,
    "avg_likes": 310,
    "avg_comments": 110,
    "avg_reposts": 176,
    "posts_per_day": 5,
    "engagement_rate": 0.61,
    "err_rate": 2.71,
    "avatar": "https://ui-avatars.com/api/?name=Mash на волне (ВК)&background=random"
  },
  {
    "platform": "vk",
    "handle": "alushta_live",
    "name": "Алушта LIVE",
    "city": "Алушта",
    "category": "Общество",
    "audience": 29000,
    "avg_views": 4800,
    "avg_likes": 65,
    "avg_comments": 24,
    "avg_reposts": 38,
    "posts_per_day": 5,
    "engagement_rate": 0.44,
    "err_rate": 2.65,
    "avatar": "https://ui-avatars.com/api/?name=Алушта LIVE&background=random"
  },
  {
    "platform": "instagram",
    "handle": "more.kryma",
    "name": "Море Крыма",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 535000,
    "avg_views": 42000,
    "avg_likes": 2900,
    "avg_comments": 70,
    "avg_reposts": 110,
    "posts_per_day": 4,
    "engagement_rate": 0.58,
    "err_rate": 7.33,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "mash_na_volne",
    "name": "Mash на волне (Insta)",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 577,
    "avg_views": 350,
    "avg_likes": 24,
    "avg_comments": 1,
    "avg_reposts": 2,
    "posts_per_day": 4,
    "engagement_rate": 4.68,
    "err_rate": 7.71,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "crimea.places",
    "name": "Места Крыма",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 34200,
    "avg_views": 5200,
    "avg_likes": 410,
    "avg_comments": 15,
    "avg_reposts": 24,
    "posts_per_day": 4,
    "engagement_rate": 1.31,
    "err_rate": 8.63,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "sasha.crimea",
    "name": "Саша Лебедева | Фотограф",
    "city": "Крым (Общий)",
    "category": "Культура",
    "audience": 12400,
    "avg_views": 2800,
    "avg_likes": 380,
    "avg_comments": 12,
    "avg_reposts": 18,
    "posts_per_day": 4,
    "engagement_rate": 3.31,
    "err_rate": 14.64,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "yalta.go",
    "name": "Ялта Go",
    "city": "Ялта",
    "category": "Туризм",
    "audience": 28500,
    "avg_views": 2400,
    "avg_likes": 210,
    "avg_comments": 7,
    "avg_reposts": 12,
    "posts_per_day": 4,
    "engagement_rate": 0.8,
    "err_rate": 9.54,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "sevastopol.inst",
    "name": "Севастополь Life",
    "city": "Севастополь",
    "category": "Общество",
    "audience": 21000,
    "avg_views": 3100,
    "avg_likes": 260,
    "avg_comments": 11,
    "avg_reposts": 15,
    "posts_per_day": 4,
    "engagement_rate": 1.36,
    "err_rate": 9.23,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "simferopol.crimea",
    "name": "Симферополь Крым",
    "city": "Симферополь",
    "category": "Общество",
    "audience": 8600,
    "avg_views": 1100,
    "avg_likes": 95,
    "avg_comments": 3,
    "avg_reposts": 6,
    "posts_per_day": 4,
    "engagement_rate": 1.21,
    "err_rate": 9.45,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "kerch.news.inst",
    "name": "Керчь Новости",
    "city": "Керчь",
    "category": "Новости",
    "audience": 4300,
    "avg_views": 750,
    "avg_likes": 60,
    "avg_comments": 2,
    "avg_reposts": 4,
    "posts_per_day": 4,
    "engagement_rate": 1.53,
    "err_rate": 8.8,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "ok",
    "handle": "group/54508933054590",
    "name": "Вести Крым (ОК)",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 16800,
    "avg_views": 2500,
    "avg_likes": 85,
    "avg_comments": 10,
    "avg_reposts": 22,
    "posts_per_day": 4,
    "engagement_rate": 0.7,
    "err_rate": 4.68,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "tvcrimea24",
    "name": "Крым 24 (ОК)",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 13500,
    "avg_views": 2100,
    "avg_likes": 75,
    "avg_comments": 8,
    "avg_reposts": 15,
    "posts_per_day": 4,
    "engagement_rate": 0.73,
    "err_rate": 4.67,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "group/54316987416629",
    "name": "Типичный Симферополь (ОК)",
    "city": "Симферополь",
    "category": "Подслушано",
    "audience": 9200,
    "avg_views": 1200,
    "avg_likes": 40,
    "avg_comments": 5,
    "avg_reposts": 8,
    "posts_per_day": 4,
    "engagement_rate": 0.58,
    "err_rate": 4.42,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "max",
    "handle": "CrimeaUA1",
    "name": "Крымский бандеровец",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 158000,
    "avg_views": 25000,
    "avg_likes": 1420,
    "avg_comments": 340,
    "avg_reposts": 480,
    "posts_per_day": 4,
    "engagement_rate": 1.42,
    "err_rate": 8.96,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "CrimeaRepublic",
    "name": "Республика Крым",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 12500,
    "avg_views": 1100,
    "avg_likes": 45,
    "avg_comments": 12,
    "avg_reposts": 18,
    "posts_per_day": 4,
    "engagement_rate": 0.6,
    "err_rate": 6.82,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "SimferopolNews",
    "name": "Новости Симферополя",
    "city": "Симферополь",
    "category": "Новости",
    "audience": 8700,
    "avg_views": 850,
    "avg_likes": 32,
    "avg_comments": 6,
    "avg_reposts": 10,
    "posts_per_day": 4,
    "engagement_rate": 0.55,
    "err_rate": 5.65,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "SevastopolNews",
    "name": "Новости Севастополя",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 9300,
    "avg_views": 920,
    "avg_likes": 38,
    "avg_comments": 8,
    "avg_reposts": 12,
    "posts_per_day": 4,
    "engagement_rate": 0.62,
    "err_rate": 6.3,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  }
];