const SCRAPED_DATA = [
  {
    "platform": "telegram",
    "handle": "rian_crimea",
    "name": "РИА Новости Крым",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 2431,
    "avg_views": 579,
    "avg_likes": 0,
    "avg_comments": 2,
    "avg_reposts": 6,
    "posts_per_day": 6,
    "engagement_rate": 0.33,
    "err_rate": 1.38,
    "avatar": "https://cdn4.telesco.pe/file/pGD-Ym6oon6lVWwD_UAAYs-kILSZ89yKwn4GpUpObFa7Je5CByR-EeLPlibT61ybHg_Sb6CAtEK6lPFtwlqr2gtQdTQB4Dyd4mLJyY3muiu5UK045g2X_RhLPYSolpffHYusL35heA8Q5gUZqLgBI26ZNaEo8X6OZQw4mlGAbAvn9JZclP671CkdFih4_f3qWurB5t3qqINj2SC330TAhvVn_QyWL_taJyd0-JyI45rn_Pg68ko96YZfgpKnsN-C1nboGDu1G-L5G_1dd3Wlk5-7iKlibBG9XgIcUuNeg2S1PkwzOZXJWTAaGBz0dH7voQS2C4uqbPHnLbzmVCJ7ng.jpg"
  },
  {
    "platform": "telegram",
    "handle": "chp_crimea",
    "name": "ЧП / Крым",
    "city": "Крым (Общий)",
    "category": "Происшествия",
    "audience": 131296,
    "avg_views": 31261,
    "avg_likes": 0,
    "avg_comments": 156,
    "avg_reposts": 375,
    "posts_per_day": 6,
    "engagement_rate": 0.4,
    "err_rate": 1.7,
    "avatar": "https://cdn4.telesco.pe/file/W1Ob_fdvU8IhAfLn71-tLy0XT5ncxvbnwHRMB4POgxSefGmAsU1NJxQrQMpklhlcS5bMG14NAX4oh3HnNiGr04yE38pUwN0XZtL65aKpzwOnEI_rZyalQWsu5Pbzy-m1vCUu4-EEjBin_4Kip6Sqd7r56RIoKdpujxCEIG30Dunu54_ekNoIocKBMxebzKgr2x523OTwNCu9oFwErYc1TpxHn6dz8FtZqWGO8Wx1IYnejDGvToQEaEErb7mCBWeBsAHpP1KTkKrEcnupPgvKp7LomTzuRwZdztPZUZYeiAsZJEBkNKrkt_3B7weruaaFLGoG2f-omzDjf17GyU1Uhg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "crimea24tv",
    "name": "Crimea24TV",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIwIiBoZWlnaHQ9IjMyMCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI%2BPGRlZnM%2BPGxpbmVhckdyYWRpZW50IGlkPSJnIiB4MT0iMCUiIHgyPSIwJSIgeTE9IjAlIiB5Mj0iMTAwJSI%2BPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzcyZDVmZCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzJhOWVmMSIvPjwvbGluZWFyR3JhZGllbnQ%2BPC9kZWZzPjxzdHlsZT50ZXh0e2ZvbnQ6NjAwIDQ0cHggLWFwcGxlLXN5c3RlbSxCbGlua01hY1N5c3RlbUZvbnQsJ1NlZ29lIFVJJyxSb2JvdG8sSGVsdmV0aWNhLEFyaWFsLHNhbnMtc2VyaWYsJ0FwcGxlIENvbG9yIEVtb2ppJywnU2Vnb2UgVUkgRW1vamknLCdTZWdvZSBVSSBTeW1ib2wnOy13ZWJraXQtdXNlci1zZWxlY3Q6bm9uZTt1c2VyLXNlbGVjdDpub25lfTwvc3R5bGU%2BPHJlY3Qgd2lkdGg9IjEwMCIgaGVpZ2h0PSIxMDAiIGZpbGw9InVybCgjZykiLz48dGV4dCB0ZXh0LWFuY2hvcj0ibWlkZGxlIiB4PSI1MCIgeT0iNjYiIGZpbGw9IiNmZmYiPkM8L3RleHQ%2BPC9zdmc%2B"
  },
  {
    "platform": "telegram",
    "handle": "minkurortov",
    "name": "Министерство туризма Крыма",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 1054,
    "avg_views": 251,
    "avg_likes": 0,
    "avg_comments": 1,
    "avg_reposts": 3,
    "posts_per_day": 6,
    "engagement_rate": 0.38,
    "err_rate": 1.59,
    "avatar": "https://cdn4.telesco.pe/file/kYmiD6LwMlUugQo5p17b8ZQ1M_0FspueIAeCdT9kSohTohh_ViAQqMD3o5LLsAmG9QvVdnKmWxUeUuG_0sMssZd0AgLDKnMuhpEmn-wGHEkMj5Lg2aVgrabsbAy0dw0MLByVpbPHwR_QPTe6z6YcWXYlerhm6HgD77AuZzsJdi563j7YoNK6OYExRgEn0KvOwXKXIUePo58yWJNP21oXGhrVcg9mxk4nbZisYjoR2tibfWauzlkKJM52hnGCRLuUgiM1iaB7V2Y69qIP9iCIo89afWMCNb1ij6o_5XOjyahm5M4sRdeKz-zpnzPPhe5jkPMZ_3noya6BqqyMXMYHiw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "sevastopol_news",
    "name": "Telegram: Contact @sevastopol_news",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "chp_sevastopol",
    "name": "ЧП / Севастополь",
    "city": "Севастополь",
    "category": "Происшествия",
    "audience": 236565,
    "avg_views": 56325,
    "avg_likes": 0,
    "avg_comments": 281,
    "avg_reposts": 675,
    "posts_per_day": 6,
    "engagement_rate": 0.4,
    "err_rate": 1.7,
    "avatar": "https://cdn4.telesco.pe/file/C-RFLUHQzAmPS-dh0VJaMww7XBh1d2Fjw2768lL-4fCysLMCQ8aTV7XacvW_R1vXpn8aZDzaPCaITh0UxUDqKPga2taHTYRg2xe_BnmPqbTaXJxZYcmAj_Is8TzZ3EHcV7Y3lsbMwm5IuQEKwh_RRIuPvt_8JFKF21mpRwmCeP9snQSM7toEnyQu6i69FdUsc-NP-qWcUME5o6FUfaaps1-hDOX6nUeCLcEuNCi5xpUX6XYAmxSTqkFgW0-Q3v3qLLwHEEfhvR2MCi9XnlScGjsOie26i-Cdt4FVeF0LUWYYv4XgOtrq5XgJ-ae27FIFSeaOEzBX3O9oWAONnm0I6Q.jpg"
  },
  {
    "platform": "telegram",
    "handle": "yalta_podslushano",
    "name": "Подслушано Ялта / Алушта",
    "city": "Ялта",
    "category": "Подслушано",
    "audience": 19000,
    "avg_views": 4524,
    "avg_likes": 0,
    "avg_comments": 22,
    "avg_reposts": 54,
    "posts_per_day": 6,
    "engagement_rate": 0.4,
    "err_rate": 1.68,
    "avatar": "https://cdn4.telesco.pe/file/mtdnsQpwsUGEf_CCMbxPW4nC7G_UdRdFXhE1Y5nbqmATORoOZSZoc6Ecivyqle1duIyAfV8hnAJMis7E87CjTTxSRmdlQhHTruVxj229Ep2H3R2XtpJTm1_jqIsr72LVk_gAswEXYbN8tu91k3iAIS0Y2egEs9IOqe-IUK2-D0JXC5WlyZKVs5qrDBCVj4RH0E9v4CuLpKfqe4x52BFiZ0pUefKBEW6RZE2fTRX_UyleBUx8DfvU_S7C1K2WVLFPTgJpvVe4Mtrk0Rfy3xNRv5eaQr6rFOnpkhlLXUI9VMvVhhCL0gZd_or_2PUTsJ6P44bP1Lv6t9zPXCQrraxGRg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "agp_yalta",
    "name": "АГП Ялта | Крым",
    "city": "Ялта",
    "category": "Новости",
    "audience": 6014,
    "avg_views": 1432,
    "avg_likes": 0,
    "avg_comments": 7,
    "avg_reposts": 17,
    "posts_per_day": 6,
    "engagement_rate": 0.4,
    "err_rate": 1.68,
    "avatar": "https://cdn4.telesco.pe/file/mA8D0QZCilreT0JNfVi3N9E_vWBMRcpCqCKCWRdrkBx_FgQfpfT8GuUX8Px1vVHbosxyzjsndGujy5XVmsCyGjr3ih1TMoxoGkzvaENHcZQIuSm1gZ-ehepxd5jigyTh9_NzeXwvOD6DfSXndn3CjU0Fec5YgAQ91qn7TvsidTinRg93NbRp_6FhiMXPwHP7q_4_vWNPUMs_9BHhdptYSC1PToQbbvtfXDrMVDNcBUneB1jWYeM3yRuaWXTqpT2ak47rPgt8in88KlAMUt-MfRFj9GeqeBn31r65quuOgU0TkDsNCvVDOs9QmnsYy3t08JDCv_SIxfMpCcwcZg7jbg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "kerch_news",
    "name": "Керчь ИНФО",
    "city": "Керчь",
    "category": "Новости",
    "audience": 6602,
    "avg_views": 1572,
    "avg_likes": 0,
    "avg_comments": 7,
    "avg_reposts": 18,
    "posts_per_day": 6,
    "engagement_rate": 0.38,
    "err_rate": 1.59,
    "avatar": "https://cdn4.telesco.pe/file/GSNtvvpydf8Vzzt_yfJGiUIUYioFOPirNHM2dUpSLzOUz5c2NKQvzx0AInNq6scTG8SgU8PiH5pD64yRmhc_zSRqe69IBTL9-yraGugdbu4K8psPZrYgKsiTDhcjt8asLagGZGat9c-d0KwKVDZuqtSbJMN0Vw4wzQ1zzBZjFRjYVYJLH3dXg6KTRtZ3pwRl5GiDl21wZgtzZi5vHuTX3JAO_YfYZGe9y0ngFfRQwXjUX2jzdVhAP7_1V4WUW1ZZgXJ4qKvisJWnfFop9riS1HplfssgVNH--rEkf8PI4U7UNE5R9k9_UWjhJKKssL7dLXavK7N2MnY8jRQ5wwNTyw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "seanewskerch",
    "name": "МыКЕРЧЬ.РФ - новости Крыма",
    "city": "Керчь",
    "category": "Новости",
    "audience": 5384,
    "avg_views": 1282,
    "avg_likes": 0,
    "avg_comments": 6,
    "avg_reposts": 15,
    "posts_per_day": 6,
    "engagement_rate": 0.39,
    "err_rate": 1.64,
    "avatar": "https://cdn4.telesco.pe/file/Zw02PSGhC9xAHo50PY5fBbpY0zuWRn_86ER39a2QXOSjzgAglRhJ2OOLJ8dM5zIgb4pDcUkZi0tC4bExh-WihnzrGGhXjXnFtLELpnhSqVUeaKaq7KI5l0QwBD82saHmApIJmBNHQe0Tp1K_c7BFvicanDx40QA6QwN4JvdP1_SoLPWzxCuoeznqY2hp9yxVjm-tWq5dWWuKQW4e30TR5TE8pJfNCpFwy__I1NElxueD4hlBy2wAzPvh0INNnCV5Q1f2zRYjKf6F2tp6Dg_sF7V_IWgQ2MRCNaFpB_UiTOj6f81ycGH26iRbfzQJxt4VanUcbEZ8Xrynbre-Lr7uHA.jpg"
  },
  {
    "platform": "telegram",
    "handle": "evpa_chp",
    "name": "Евпатория ЧП 🔥",
    "city": "Евпатория",
    "category": "Происшествия",
    "audience": 12432,
    "avg_views": 2960,
    "avg_likes": 0,
    "avg_comments": 14,
    "avg_reposts": 35,
    "posts_per_day": 6,
    "engagement_rate": 0.39,
    "err_rate": 1.66,
    "avatar": "https://cdn4.telesco.pe/file/bNopJVYkT0s2rl0NBI8fuxSAiQ1__JktzqrF4vng0uxlcE03byMOe7n5wsv4WWoeJbF60QUweDNOVVxabqcQsaO0icRJzCF5odMIglqBmfnpPR1aFcRB8nAbL5YiTZlU9l46pwl6TGfjqez70GmVcmojHOUHSQ5vP7rB9H7X0Dwv6a71Uwl9vknNjBNwF3SMyvSI2nNDsU48n7rXeW4YPS7T0iccFH0zZ8PfLbeP6qLTxorILl5WpSrQc5NnqcbeeicF9zEtyuCj-uLfljZnB-8E3nqh-xhlf18SBaX_q36onUI6KLT56tNqgT2UQeiXND7G6GOpj4XHZebZvKxwoA.jpg"
  },
  {
    "platform": "telegram",
    "handle": "evp_pod",
    "name": "📣 Евпатория Подслушано (Крым)",
    "city": "Евпатория",
    "category": "Подслушано",
    "audience": 3032,
    "avg_views": 722,
    "avg_likes": 0,
    "avg_comments": 3,
    "avg_reposts": 8,
    "posts_per_day": 6,
    "engagement_rate": 0.36,
    "err_rate": 1.52,
    "avatar": "https://cdn4.telesco.pe/file/gYn8_T_fVdWvGqtIPyNtH8_12-ZUwxtfTwZ3gLgyErsd7Ux-mB5vrh7i70ZteFaH_l_LAxcAYAXLRandy8TN1QMfzXSd615Q2KgsQZALpaHHzVaDY5c-eh09vwrbF5pbzGKStmiMWAKX0hoDGyjkM178qu69BS4JlYeYCxOTBVvIaaMzY-0NmZ5ccJTc2d_1LExZ-TYOuGiwfirHdO6JtOtGmwtMV5ph650WqwrbFx-hmSRNrDAxtmqUPkDvWJhuoljvHxO6EoxyLKOfPhrKhLrfdfxqY16gqXoTucUpu1jIIHmRIixINhVfLCV6AeLL07gi5ET8aBKNOxnno3l7rg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "feodosia_news",
    "name": "Новость|Феодосия",
    "city": "Феодосия",
    "category": "Новости",
    "audience": 109,
    "avg_views": 26,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0.0,
    "err_rate": 0.0,
    "avatar": "https://cdn4.telesco.pe/file/o7vjyICJMxGetZuFTMdQKMJMXI6NJxGpT7k-pM7vSiihRCRpaITWO-dWcTWZTSlWPHMm4rbSHsAbi3azjCk-ovbUohZc6ycH9zhKZEeXu4fStPVqUmYm5MEtECFhHLZRZ_S8veiv1kHsxyinkvxzlP_2AJIED-xOQ_ALbeDgkmOT3c2BpgLYUMIwy6Fjhrxccy2F8sL5hYIUfEjlan200YsHw8EL7e1YjV7JFT0CRUDOuXcXpG9_6TgkIoDPCWXZCxT_eWezWLrwAK0ErVKTqkSjLYRZKZ4VQX74Q37TX-O_LXsSrxT-HRhhjveB3ZEwgbatqp1LzWwPgUgIck7GSw.jpg"
  },
  {
    "platform": "telegram",
    "handle": "feodosia_chp",
    "name": "Telegram: Contact @feodosia_chp",
    "city": "Феодосия",
    "category": "Происшествия",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "mash_na_volne",
    "name": "Mash на волне",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 226955,
    "avg_views": 54037,
    "avg_likes": 0,
    "avg_comments": 270,
    "avg_reposts": 648,
    "posts_per_day": 6,
    "engagement_rate": 0.4,
    "err_rate": 1.7,
    "avatar": "https://cdn4.telesco.pe/file/UygTT0uZB3oBtkyr1HwntqDEwccktqNs1sM1m3W3o9oXHZH65l6Q2mX8ZfOfokLM2-O8gpcVQk8fUm1eA5a_qWUl7KnnyavuHYPZvl0cUvcCzWEMrpEZC3k6c6_ehL1tKAWcD_4FH_MD2tpkzi4OjyRDyhz_oJbX43NRHpBTXI9rhe_GBux9JuyO1vtf6P1GhlBHaiNAyz6u9-hg4vnT5a1JEMXkWFK22SfdpGHvOUle-w4zLTbvMBVViCxKdAYmEWuOQkH7Hpc7IZqLxNZ2e0WBZDUyQMv_cjUwJvcIP9FXpellmd_T-sLscqrfJZypGoN_UQtKZ_REjYtaJ8gclg.jpg"
  },
  {
    "platform": "telegram",
    "handle": "crimeaincident",
    "name": "Telegram: Contact @crimeaincident",
    "city": "Крым (Общий)",
    "category": "Происшествия",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "simf_overheard",
    "name": "Telegram: Contact @simf_overheard",
    "city": "Симферополь",
    "category": "Подслушано",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "alushta_overheard_tg",
    "name": "Telegram: Contact @alushta_overheard_tg",
    "city": "Алушта",
    "category": "Подслушано",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "crimea_chp_tg",
    "name": "Telegram: Contact @crimea_chp_tg",
    "city": "Крым (Общий)",
    "category": "Происшествия",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "simferopol_news_tg",
    "name": "Telegram: Contact @simferopol_news_tg",
    "city": "Симферополь",
    "category": "Новости",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "sevastopol_incidents",
    "name": "Telegram: Contact @sevastopol_incidents",
    "city": "Севастополь",
    "category": "Происшествия",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "sudak_news_tg",
    "name": "Telegram: Contact @sudak_news_tg",
    "city": "Судак",
    "category": "Новости",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "saki_overheard_tg",
    "name": "Telegram: Contact @saki_overheard_tg",
    "city": "Саки",
    "category": "Подслушано",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "dzhankoy_news_tg",
    "name": "Telegram: Contact @dzhankoy_news_tg",
    "city": "Джанкой",
    "category": "Новости",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "crimea_fortress",
    "name": "Telegram: Contact @crimea_fortress",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "telegram",
    "handle": "crimea_top_travel",
    "name": "Telegram: Contact @crimea_top_travel",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 0,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 6,
    "engagement_rate": 0,
    "err_rate": 0,
    "avatar": "https://telegram.org/img/t_logo_2x.png"
  },
  {
    "platform": "vk",
    "handle": "typical_simferopol",
    "name": "Это Симферополь, детка! [Типичный Симферополь]",
    "city": "Симферополь",
    "category": "Подслушано",
    "audience": 1000,
    "avg_views": 67,
    "avg_likes": 4,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.4,
    "err_rate": 5.97,
    "avatar": "http://sun9-63.userapi.com/s/v1/ig2/vB6uKfAdvlunmx_DgRbqqXKgmQILAQR3u9eVjnaVL-iG8BKG110Kreytk_UAE3BqDQVN_Z7PWq2Qc2x0EyNrn4D0.jpg?quality=96&crop=0,0,230,230&as=32x32,48x48,72x72,108x108,160x160&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "simferopol_city",
    "name": "Мой Симферополь",
    "city": "Симферополь",
    "category": "Общество",
    "audience": 4750,
    "avg_views": 458,
    "avg_likes": 19,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.4,
    "err_rate": 4.15,
    "avatar": "http://sun9-75.userapi.com/impf/R2KAqxbio05geH1mpTQH8GVCcBRY4QDw3lP3Tw/mm6J2lcfqfk.jpg?size=1920x768&quality=95&crop=0,213,1280,511&sign=4c3fc6a623b3a509ac4abec7161fc651&type=cover_group"
  },
  {
    "platform": "vk",
    "handle": "sevastopol_groupe",
    "name": "Севастополь",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 96298,
    "avg_views": 5020,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0.0,
    "avatar": "http://sun1-14.userapi.com/impf/UKQ19dMlN3BB7Lv_4S1RikhOQhksnqpb1cAU8A/LXvwjCuAP3Q.jpg?size=1818x606&quality=95&crop=0,0,1590,530&sign=542db9aaaacba1dabd905946b4f41a9a&type=cover_group"
  },
  {
    "platform": "vk",
    "handle": "sevas_92",
    "name": "Подслушано Севастополь",
    "city": "Севастополь",
    "category": "Подслушано",
    "audience": 114775,
    "avg_views": 243,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0.0,
    "avatar": "http://sun9-68.userapi.com/s/v1/ig2/_wbbC5VK-_0A0up0piPGYU_9lpgTmqagOcxXuBtRZlpkQIadgXPpVIwSl6txgz8Oqw8d4y4D_J4H9SR_PpdKPcOS.jpg?quality=95&crop=0,0,1080,1080&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720,1080x1080&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "typical_sevastopol",
    "name": "✪  ✪ Паблик 3 ✪ 2026",
    "city": "Севастополь",
    "category": "Общество",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "http://sun9-86.userapi.com/impg/9FmuZgmL8ElIl3ap2VNqqvCJuR3XBTRcL5RstQ/IkJdt6c43WI.jpg?quality=96&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360&sign=80af15cf714eb8b0c9b0fb180d3fb037&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "podslushano_yalta",
    "name": "ПОДСЛУШАНО ЯЛТА",
    "city": "Ялта",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=ПОДСЛУШАНО ЯЛТА&background=random"
  },
  {
    "platform": "vk",
    "handle": "yalta_gorod_schastya",
    "name": "Филиал ПОДСЛУШАНО в ЯЛТЕ",
    "city": "Ялта",
    "category": "Туризм",
    "audience": 15000,
    "avg_views": 12,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0.0,
    "avatar": "http://sun9-79.userapi.com/s/v1/ig1/u1qa5FAI-geuGmqTNorK4kG_xgSaAYjqi3FAi-cwb7yHmcC-cABvQ_mjTeH937gQpcq4v_3y.jpg?quality=96&crop=0,0,720,720&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720&ava=1&cs=240x240"
  },
  {
    "platform": "vk",
    "handle": "podslushano_kerch",
    "name": "ПОДСЛУШАНО | КЕРЧЬ",
    "city": "Керчь",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=ПОДСЛУШАНО | КЕРЧЬ&background=random"
  },
  {
    "platform": "vk",
    "handle": "kerch_segodnya",
    "name": "КЕРЧЬ СЕГОДНЯ",
    "city": "Керчь",
    "category": "Новости",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=КЕРЧЬ СЕГОДНЯ&background=random"
  },
  {
    "platform": "vk",
    "handle": "evpator_podslushano",
    "name": "Евпатория | Подслушано",
    "city": "Евпатория",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=Евпатория | Подслушано&background=random"
  },
  {
    "platform": "vk",
    "handle": "evpator_ru",
    "name": "Евпатория -  наш город !!!",
    "city": "Евпатория",
    "category": "Новости",
    "audience": 39222,
    "avg_views": 202,
    "avg_likes": 3,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.01,
    "err_rate": 1.49,
    "avatar": "http://sun1-55.userapi.com/QK-pgYWE0orEYxJfRLpw-eaUh5Z0C0tKKQgX5A/m-9qfd9jjaM.jpg"
  },
  {
    "platform": "vk",
    "handle": "podslushano_feodosiya",
    "name": "Подслушано Феодосия",
    "city": "Феодосия",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=Подслушано Феодосия&background=random"
  },
  {
    "platform": "vk",
    "handle": "mash.na.volne",
    "name": "Mash на волне (ВК)",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=Mash на волне (ВК)&background=random"
  },
  {
    "platform": "vk",
    "handle": "alushta_live",
    "name": "Алушта LIVE",
    "city": "Алушта",
    "category": "Общество",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=Алушта LIVE&background=random"
  },
  {
    "platform": "vk",
    "handle": "sudak_overheard",
    "name": "Подслушано Судак",
    "city": "Судак",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=Подслушано Судак&background=random"
  },
  {
    "platform": "vk",
    "handle": "bakhchisaray_live",
    "name": "Бахчисарай LIVE",
    "city": "Бахчисарай",
    "category": "Общество",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=Бахчисарай LIVE&background=random"
  },
  {
    "platform": "vk",
    "handle": "saki_overheard_vk",
    "name": "Подслушано Саки (ВК)",
    "city": "Саки",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=Подслушано Саки (ВК)&background=random"
  },
  {
    "platform": "vk",
    "handle": "dzhankoy_overheard_vk",
    "name": "Подслушано Джанкой (ВК)",
    "city": "Джанкой",
    "category": "Подслушано",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=Подслушано Джанкой (ВК)&background=random"
  },
  {
    "platform": "vk",
    "handle": "crimea_emergency",
    "name": "МЧС Крыма / Новости",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 15000,
    "avg_views": 0,
    "avg_likes": 0,
    "avg_comments": 0,
    "avg_reposts": 0,
    "posts_per_day": 5,
    "engagement_rate": 0.0,
    "err_rate": 0,
    "avatar": "https://ui-avatars.com/api/?name=МЧС Крыма / Новости&background=random"
  },
  {
    "platform": "instagram",
    "handle": "crimea_life",
    "name": "Крым Life",
    "city": "Крым (Общий)",
    "category": "Стиль жизни",
    "audience": 78300,
    "avg_views": 18200,
    "avg_likes": 2400,
    "avg_comments": 85,
    "avg_reposts": 110,
    "posts_per_day": 4,
    "engagement_rate": 3.31,
    "err_rate": 14.26,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "more.kryma",
    "name": "Море Крыма",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 112000,
    "avg_views": 32000,
    "avg_likes": 4100,
    "avg_comments": 140,
    "avg_reposts": 250,
    "posts_per_day": 4,
    "engagement_rate": 4.01,
    "err_rate": 14.03,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "typical_simferopol",
    "name": "Типичный Симферополь",
    "city": "Симферополь",
    "category": "Общество",
    "audience": 43500,
    "avg_views": 8900,
    "avg_likes": 1150,
    "avg_comments": 42,
    "avg_reposts": 65,
    "posts_per_day": 4,
    "engagement_rate": 2.89,
    "err_rate": 14.12,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "sevastopol_life",
    "name": "Севастополь Life",
    "city": "Севастополь",
    "category": "Общество",
    "audience": 52100,
    "avg_views": 11200,
    "avg_likes": 1540,
    "avg_comments": 58,
    "avg_reposts": 90,
    "posts_per_day": 4,
    "engagement_rate": 3.24,
    "err_rate": 15.07,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "yalta_life",
    "name": "Ялта Life",
    "city": "Ялта",
    "category": "Общество",
    "audience": 61200,
    "avg_views": 14500,
    "avg_likes": 1920,
    "avg_comments": 74,
    "avg_reposts": 125,
    "posts_per_day": 4,
    "engagement_rate": 3.46,
    "err_rate": 14.61,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "kerch_info",
    "name": "Керчь Инфо",
    "city": "Керчь",
    "category": "Новости",
    "audience": 31400,
    "avg_views": 6200,
    "avg_likes": 790,
    "avg_comments": 31,
    "avg_reposts": 40,
    "posts_per_day": 4,
    "engagement_rate": 2.74,
    "err_rate": 13.89,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "mash_na_volne",
    "name": "Mash на волне (Insta)",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 95000,
    "avg_views": 41000,
    "avg_likes": 5300,
    "avg_comments": 190,
    "avg_reposts": 320,
    "posts_per_day": 4,
    "engagement_rate": 6.12,
    "err_rate": 14.17,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "crimea_beauty",
    "name": "Красивый Крым",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 68400,
    "avg_views": 15600,
    "avg_likes": 2200,
    "avg_comments": 80,
    "avg_reposts": 180,
    "posts_per_day": 4,
    "engagement_rate": 3.6,
    "err_rate": 15.77,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "yalta_go",
    "name": "Ялта Go",
    "city": "Ялта",
    "category": "Туризм",
    "audience": 28500,
    "avg_views": 5900,
    "avg_likes": 920,
    "avg_comments": 45,
    "avg_reposts": 70,
    "posts_per_day": 4,
    "engagement_rate": 3.63,
    "err_rate": 17.54,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "instagram",
    "handle": "crimea_explore",
    "name": "Исследуй Крым",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 41200,
    "avg_views": 9800,
    "avg_likes": 1450,
    "avg_comments": 50,
    "avg_reposts": 110,
    "posts_per_day": 4,
    "engagement_rate": 3.91,
    "err_rate": 16.43,
    "avatar": "https://img.icons8.com/color/150/instagram-new.png"
  },
  {
    "platform": "ok",
    "handle": "vesticrimea",
    "name": "Вести Крым",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 24500,
    "avg_views": 4800,
    "avg_likes": 120,
    "avg_comments": 15,
    "avg_reposts": 45,
    "posts_per_day": 4,
    "engagement_rate": 0.73,
    "err_rate": 3.75,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "crimea24tv",
    "name": "Крым 24",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 18200,
    "avg_views": 3500,
    "avg_likes": 95,
    "avg_comments": 12,
    "avg_reposts": 30,
    "posts_per_day": 4,
    "engagement_rate": 0.75,
    "err_rate": 3.91,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "typical_simferopol",
    "name": "Типичный Симферополь",
    "city": "Симферополь",
    "category": "Подслушано",
    "audience": 12500,
    "avg_views": 2100,
    "avg_likes": 55,
    "avg_comments": 8,
    "avg_reposts": 18,
    "posts_per_day": 4,
    "engagement_rate": 0.65,
    "err_rate": 3.86,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "crimea_news_ok",
    "name": "Новости Крыма",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 31200,
    "avg_views": 6100,
    "avg_likes": 160,
    "avg_comments": 22,
    "avg_reposts": 50,
    "posts_per_day": 4,
    "engagement_rate": 0.74,
    "err_rate": 3.8,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "sevastopol_news_ok",
    "name": "Новости Севастополя",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 15400,
    "avg_views": 2900,
    "avg_likes": 75,
    "avg_comments": 10,
    "avg_reposts": 20,
    "posts_per_day": 4,
    "engagement_rate": 0.68,
    "err_rate": 3.62,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "yalta_news_ok",
    "name": "Новости Ялты OK",
    "city": "Ялта",
    "category": "Новости",
    "audience": 8900,
    "avg_views": 1800,
    "avg_likes": 42,
    "avg_comments": 5,
    "avg_reposts": 12,
    "posts_per_day": 4,
    "engagement_rate": 0.66,
    "err_rate": 3.28,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "ok",
    "handle": "kerch_news_ok",
    "name": "Новости Керчи OK",
    "city": "Керчь",
    "category": "Новости",
    "audience": 10200,
    "avg_views": 2200,
    "avg_likes": 48,
    "avg_comments": 6,
    "avg_reposts": 14,
    "posts_per_day": 4,
    "engagement_rate": 0.67,
    "err_rate": 3.09,
    "avatar": "https://img.icons8.com/color/150/odnoklassniki.png"
  },
  {
    "platform": "max",
    "handle": "CrimeaUA1",
    "name": "Крымский бандеровец",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 158000,
    "avg_views": 25000,
    "avg_likes": 1420,
    "avg_comments": 340,
    "avg_reposts": 480,
    "posts_per_day": 4,
    "engagement_rate": 1.42,
    "err_rate": 8.96,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "CrimeaRepublic",
    "name": "Республика Крым",
    "city": "Крым (Общий)",
    "category": "Новости",
    "audience": 12500,
    "avg_views": 1100,
    "avg_likes": 45,
    "avg_comments": 12,
    "avg_reposts": 18,
    "posts_per_day": 4,
    "engagement_rate": 0.6,
    "err_rate": 6.82,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "SimferopolNews",
    "name": "Новости Симферополя",
    "city": "Симферополь",
    "category": "Новости",
    "audience": 8700,
    "avg_views": 850,
    "avg_likes": 32,
    "avg_comments": 6,
    "avg_reposts": 10,
    "posts_per_day": 4,
    "engagement_rate": 0.55,
    "err_rate": 5.65,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "SevastopolNews",
    "name": "Новости Севастополя",
    "city": "Севастополь",
    "category": "Новости",
    "audience": 9300,
    "avg_views": 920,
    "avg_likes": 38,
    "avg_comments": 8,
    "avg_reposts": 12,
    "posts_per_day": 4,
    "engagement_rate": 0.62,
    "err_rate": 6.3,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "CrimeaIncidentMax",
    "name": "ЧП Крым Max",
    "city": "Крым (Общий)",
    "category": "Происшествия",
    "audience": 14200,
    "avg_views": 3800,
    "avg_likes": 210,
    "avg_comments": 45,
    "avg_reposts": 72,
    "posts_per_day": 4,
    "engagement_rate": 2.3,
    "err_rate": 8.61,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "YaltaNewsMax",
    "name": "Ялта Новости Max",
    "city": "Ялта",
    "category": "Новости",
    "audience": 7500,
    "avg_views": 790,
    "avg_likes": 28,
    "avg_comments": 5,
    "avg_reposts": 8,
    "posts_per_day": 4,
    "engagement_rate": 0.55,
    "err_rate": 5.19,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "CrimeaTravelMax",
    "name": "Крым Путешествия Max",
    "city": "Крым (Общий)",
    "category": "Туризм",
    "audience": 18500,
    "avg_views": 2100,
    "avg_likes": 98,
    "avg_comments": 15,
    "avg_reposts": 25,
    "posts_per_day": 4,
    "engagement_rate": 0.75,
    "err_rate": 6.57,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  },
  {
    "platform": "max",
    "handle": "SimferopolIncidentMax",
    "name": "ЧП Симферополь Max",
    "city": "Симферополь",
    "category": "Происшествия",
    "audience": 11200,
    "avg_views": 2900,
    "avg_likes": 150,
    "avg_comments": 28,
    "avg_reposts": 40,
    "posts_per_day": 4,
    "engagement_rate": 1.95,
    "err_rate": 7.52,
    "avatar": "https://img.icons8.com/color/150/twitter--v1.png"
  }
];